# @package _global_

dataset_name: zju_multi_${model.gaussian.decomp_type}_R${model.gaussian.R}_${texture_name}_iter100

test_interval: 1000


dataset:
  name: zjumocap_multi
  root_dir: "/path/to/datasets/zju_mocap_arah"
  subjects: ["CoreView_377", "CoreView_386", "CoreView_387", "CoreView_392", "CoreView_393", "CoreView_394"]
  refine: false
  # test_subject: "CoreView_377"

  train_views: [ '1' ]
  val_views: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['1']

  train_frames: [ 0, 0, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 570, 30]
    video: [0, 570, 1]
    all: [0, 570, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512
  img_HW:
    - 1024
    - 1024

  lanczos: false
  resolution: -1
  white_background: true
  data_device: cuda
  eval: false

  preload: false

model:
  multigaussian: True
  gaussian:
    R: 100
    decomp_type: CP
  texture:
    identity_dim: 0
  deformer:
    non_rigid:
      identity_dim: 0
